title: Portfólio Engenharia de Dados
markdown: kramdown

hero:
  greeting: "Olá, eu sou"
  name: "Rodrigo Silva Rocha"
  subtitle: "Engenheiro de Dados —  construindo pipelines robustos e arquiteturas de dados escaláveis"
  cta_text: "Ver Projetos"
  cta_link: "#projects"
  background: "/assets/img/header.jpeg"

collections:
  projects:
    output: true
    permalink: /projects/:name/


            <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
          
skills:
  - name: Python
    icon: https://devicon-website.vercel.app/api/python/plain.svg?color=%2367E8F9
  
  - name: Airflow
    icon: https://cdn.simpleicons.org/apacheairflow/67e8f9

  - name: PDI
    icon: /assets/devicons/pdi.png

  - name: MySQL
    icon: https://devicon-website.vercel.app/api/mysql/plain.svg?color=%2367E8F9
  
  - name: Sql Server
    icon: https://devicon-website.vercel.app/api/microsoftsqlserver/plain.svg?color=%2367E8F9

  - name: Oracle
    icon: https://devicon-website.vercel.app/api/oracle/original.svg?color=%2367E8F9
  
  - name: MongoDb
    icon: https://devicon-website.vercel.app/api/mongodb/plain.svg?color=%2367E8F9

  - name: Redis
    icon: https://devicon-website.vercel.app/api/redis/plain.svg?color=%2367E8F9

  - name: Docker
    icon: https://cdn.simpleicons.org/docker/67e8f9

  - name: Kafka
    icon: https://cdn.simpleicons.org/apachekafka/67e8f9

  - name: dbt
    icon: /assets/devicons/dbt.png






contacts:
  email: silva.rodrigo31@gmail.com
  github: https://github.com/rodrigorocha1234
  linkedin: https://www.linkedin.com/in/rodrigo-rocha-dados/



exclude:
  - Gemfile
  - Gemfile.lock